from typing import Any

class Locale:
    def __init__(self, *args: Any) -> None: ...
    def getName(self) -> str: ...
    def getCountry(self) -> str: ...
    def getLanguage(self) -> str: ...

class Formattable:
    def __init__(self, value: Any) -> None: ...

class MessageFormat:
    def __init__(self, pattern: str, locale: Locale) -> None: ...
    def format(self, args: list[Formattable]) -> str: ...
