line-length = 88
target-version = "py312"

[format]
line-ending = "native"
quote-style = "single"
indent-style = "space"

[lint]
select = [
    "F",
    "E",
    "I",
    "UP",
    "B",
    "SIM",
    "C4",
    "PERF",
    "PTH",
    "RET",
    "N",
    "PLC",
    "PLE",
    "PLW",
    "RUF",
    "S",
    "FAST",
    "A",
    "PT",
    "ASYNC",
    "DTZ",
    "LOG",
    "G",
    "ICN",
    "T20",
]
ignore = [
    "hardcoded-bind-all-interfaces",
    "suspicious-non-cryptographic-random-usage",
    "too-many-statements-in-try-clause",
    "raise-vanilla-args",
    "zip-without-explicit-strict",
    "ambiguous-variable-name",
    "quoted-annotation",
    "invalid-function-name",
    "hardcoded-password-string",
]
preview = true

[lint.per-file-ignores]
"typings/*" = ["ALL"]
"tests/*" = ["ARG", "assert", "D", "hardcoded-password-string"]
"src/poxbot/legacy_cogs/**" = ["ALL"]
"cogs-legacy/**" = ["ALL"]
"src/poxbot/platforms/discord/extensions/*" = ["D", "implicit-return"]

[lint.pycodestyle]
max-doc-length = 128

[lint.pydocstyle]
convention = "google"

[lint.flake8-copyright]
author = "p0x38"
