import contextlib
from datetime import timedelta
from time import time
from typing import Any

from discord import (
    Color,
    Embed,
    File,
    Interaction,
    app_commands,
)
from discord.ext import commands

from ....application import PoxBot
from ....features.tts.manager import TTSManager
from ....shared.enums.tts import TTSEngineType
from ....shared.exceptions.tts_error import EmptyInputError
from ....shared.utils.fuzzy_search import fuzzy_search_objects


class TextToSpeechCog(commands.Cog):
    def __init__(self, bot):
        self.bot: PoxBot = bot
        self.tts_manager = TTSManager(bot)

    async def cog_load(self):
        await self.tts_manager.cog_load()

    async def googletts_autocomplete(
        self,
        _interaction: Interaction,
        current: str,
    ) -> list[app_commands.Choice[str]]:
        google_engine = self.tts_manager.engines.get(TTSEngineType.GOOGLE_TTS)

        gtts_languages = getattr(google_engine, 'gtts_languages', {})

        matched_items = fuzzy_search_objects(
            current,
            gtts_languages.items(),
            lambda item: [item[0], item[1]],
        )
        return [
            app_commands.Choice(name=full, value=code) for code, full in matched_items
        ]

    async def edgetts_autocomplete(
        self,
        _interaction: Interaction,
        current: str,
    ) -> list[app_commands.Choice[str]]:
        edge_engine = self.tts_manager.engines.get(TTSEngineType.EDGE_TTS)

        edge_tts_voices = getattr(edge_engine, 'edge_tts_voices', {})

        matched_items = fuzzy_search_objects(
            current,
            edge_tts_voices,
            lambda v: [getattr(v, 'name', ''), getattr(v, 'friendly_name', '')],
        )
        return [
            app_commands.Choice(
                name=getattr(v, 'friendly_name', ''),
                value=getattr(v, 'name', ''),
            )
            for v in matched_items
        ]

    async def pockettts_autocomplete(
        self,
        _interaction: Interaction,
        current: str,
    ) -> list[app_commands.Choice[str]]:
        pocket_engine = self.tts_manager.engines.get(TTSEngineType.POCKET_TTS)

        custom_models = getattr(pocket_engine, 'custom_models', [])
        builtin_models = getattr(pocket_engine, 'builtin_models', [])

        all_models = custom_models + builtin_models

        matched_models = fuzzy_search_objects(
            current,
            all_models,
            lambda m: [m.name, m.friendly_name],
        )

        choices = []
        for model_info in matched_models:
            if model_info in custom_models:
                display_name = f'{model_info.friendly_name} (Custom)'
            else:
                display_name = f'{model_info.name} (Built-in)'

            choices.append(
                app_commands.Choice(name=display_name, value=str(model_info.model)),
            )
        return choices

    async def _generate_tts(
        self, interaction: Interaction, request_data: dict[str, Any]
    ):
        await interaction.response.defer(thinking=True)

        with contextlib.suppress(Exception):
            await self.tts_manager.generate_speech(request_data)

    async def generate_tts(
        self,
        interaction: Interaction,
        text: str,
        engine: TTSEngineType,
        voice: str | None = None,
    ):
        loc = await self.bot.get_locale(interaction)
        await interaction.response.defer(thinking=True)

        embed = Embed()

        def _assert_valid_result(res: Any) -> None:
            if not res or not getattr(res, 'output', None):
                raise EmptyInputError()

        try:
            data = {'input': text, 'engine': engine, 'voice': voice}
            result = await self.tts_manager.generate_speech(data)

            _assert_valid_result(result)

            filename = (
                f'{str(engine.name).replace(" ", "")}_{int(time())!s}.'
                + result.media_type
            )

            file = File(result.output, filename)

            embed.color = Color.green()
            embed.set_footer(
                text=f'Generated by {interaction.user.display_name}',
                icon_url=interaction.user.display_avatar.url,
            )

            duration = result.metrics.duration
            chunk_count = result.metrics.chunk_count

            temp_tts = {
                'tts_input': input,
                'tts_engine': str(engine.name),
                'tts_voice': voice if voice else 'None',
            }

            if isinstance(duration, timedelta):
                temp_tts['tts_generation_took'] = f'{duration.total_seconds():.3f}'

            if chunk_count > 0:
                temp_tts['tts_chunk'] = str(chunk_count)

            temp_tts = self.bot.internal_translator.translate_map(temp_tts, str(loc))

            for name, value in temp_tts.items():
                embed.add_field(name=name, value=value, inline=True)

            await interaction.followup.send(embed=embed, file=file)
        except Exception as e:
            self.bot.logger.exception('Unexpected exception raised')
            embed.color = Color.red()
            embed.title = f'Exception thrown: {e.__class__.__name__}'
            embed.description = str(e)

            await interaction.followup.send(embed=embed)


async def setup(bot):
    await bot.add_cog(TextToSpeechCog(bot))
